void lowpass_init(float f0, float fs);
void highpass_init(float f0, float fs);
void bandstop_init(float f0, float fw, float fs);
void bandpass_init(float f0, float fw, float fs);
float lowpass(float x1);
float highpass(float x1);
float bandpass(float x1);
float bandstop(float x1);
float movingAvg(float *ptrArrNumbers, double *ptrSum, int pos, int len, float nextNum);
void reset_filter();
